In [ ]:
>>> a = np.random.rand(8,13,13)
>>> b = np.random.rand(8,13,13)
print(np.shape(a@b))
print(np.shape(np.matmul(a, b)))

In [ ]:
np.shape(c)

In [ ]:
np.shape(d)

In [ ]:
print(np.shape(e))
e

In [ ]:
a = np.random.rand(2,3,3)
b = np.random.rand(2,3,3)
c = (a@b)
d = np.dot(a,b)
e = np.matmul(a,b)

## ----------------------------------------------------------------------------------------------------------------------------------

In [ ]:
# Assignment # 1
# Create a 4 dimensional array and experiment to access various different values

# Assignment # 2
# Download "medical insurance claim fraud.csv" from kaggle.com
# Create DataFrame from this downloaded csv

# Assignment # 3
# Create DataFrame from any of your existing SQL Server table 

In [ ]:
array = np.array([[[[1, 2, 3], [20, 57, 78]], [[20, 8, 39], [58, 47, 81]], [[52,63, 45], [89, 96 ,12]]], [[1, 2, 3], [20, 57, 78]], [[20, 8, 39], [58, 47, 81]], [[52,63, 45], [89, 96 ,12]] ], [[1, 2, 3], [20, 57, 78]], [[20, 8, 39], [58, 47, 81]], [[52,63, 45], [89, 96 ,12]]]) 

In [ ]:
array = np.array([[[[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]]], [[[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]]]])

In [ ]:
print(np.shape(array))
array

In [ ]:
#########################################################################################################################

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv(r"medical_aid_claims.csv")

In [ ]:
df

In [ ]:
df.shape

In [ ]:
#########################################################################################################################

In [ ]:
# how to get data from sql server
import pyodbc
server = 'DESKTOP-OLDBM90\SQLEXPRESS'
dbname = 'try_db'
cn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server}; SERVER= ' + server + ';DATABASE='+ dbname + ' ;Trusted_Connection=yes;')
crsr = cn.cursor()

qry='select * from table_1'

query = pd.read_sql_query(qry,cn)

df = pd.DataFrame(query,columns=['Name','Age','Matches','Country'])

print(df)
cn.close()

## ----------------------------------------------------------------------------------------------------------------------------------

In [ ]:
# Assignment # 1
# Create a Pandas DataFrame from Numpy array which you have created in earlier assignment

In [1]:
import numpy as np
import pandas as pd

In [2]:
array = np.array([[[[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]]], [[[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]], [[1,2,3] , [5,6,7]]]])
print(np.shape(array))
print()
print(array)

(2, 4, 2, 3)

[[[[1 2 3]
   [5 6 7]]

  [[1 2 3]
   [5 6 7]]

  [[1 2 3]
   [5 6 7]]

  [[1 2 3]
   [5 6 7]]]


 [[[1 2 3]
   [5 6 7]]

  [[1 2 3]
   [5 6 7]]

  [[1 2 3]
   [5 6 7]]

  [[1 2 3]
   [5 6 7]]]]


In [4]:
# Error : The Normal Way Does Not Work With Anything More Than A 2D Array


# a_df = pd.DataFrame(array)
# a_df = pd.DataFrame(array, columns = ['w', 'x', 'y', 'z'])

im = array
arr = np.column_stack(list(map(np.ravel, np.meshgrid(*map(np.arange, im.shape), indexing="ij"))) + [im.ravel()])
pd.DataFrame(arr, columns = ['mode', 'x', 'y', 'z', 'val'])



mode  x  y  z  val
0      0  0  0  0    1
1      0  0  0  1    2
2      0  0  0  2    3
3      0  0  1  0    5
4      0  0  1  1    6
5      0  0  1  2    7
6      0  1  0  0    1
7      0  1  0  1    2
8      0  1  0  2    3
9      0  1  1  0    5
10     0  1  1  1    6
11     0  1  1  2    7
12     0  2  0  0    1
13     0  2  0  1    2
14     0  2  0  2    3
15     0  2  1  0    5
16     0  2  1  1    6
17     0  2  1  2    7
18     0  3  0  0    1
19     0  3  0  1    2
20     0  3  0  2    3
21     0  3  1  0    5
22     0  3  1  1    6
23     0  3  1  2    7
24     1  0  0  0    1
25     1  0  0  1    2
26     1  0  0  2    3
27     1  0  1  0    5
28     1  0  1  1    6
29     1  0  1  2    7
30     1  1  0  0    1
31     1  1  0  1    2
32     1  1  0  2    3
33     1  1  1  0    5
34     1  1  1  1    6
35     1  1  1  2    7
36     1  2  0  0    1
37     1  2  0  1    2
38     1  2  0  2    3
39     1  2  1  0    5
40     1  2  1  1    6
41     1  2  1  2    7
42     1  3  0  0    1
43     1  3  0  1    2
44     1  3  0  2    3
45     1  3  1  0    5
46     1  3  1  1    6
47     1  3  1  2    7

In [ ]:
df

In [ ]:
array_2d = np.array([[1, 2], [3, 4]])
print(np.shape(array_2d))
print()
print(array_2d)

In [ ]:
a2d_df = pd.DataFrame(array_2d)
a2d_df

In [ ]:
a2d_df = pd.DataFrame(array_2d, columns=['C1', 'C2'])
a2d_df

In [ ]:
# Assignment # 2
# Study and reasearch online for the difference between .loc and .iloc

"""
Loc is label-based, which means that you have to specify rows and columns based on their row and column labels (Strings)
                                                                                                
Iloc is integer position-based, so you have to specify rows and columns by their integer position values (Integer)
"""

In [ ]:
# Assignment # 3
# Practice multiple conditions on the dataset which you have downloaded - with and , or , ~

In [ ]:
# Loading DataBase

df = pd.read_csv(r"medical_aid_claims.csv")
pd.set_option("display.max_columns",100)
df.head()

In [ ]:
age_premium_filter = (df["number_of_claims"] > 1) & (df["cause"] == "other")
df[age_premium_filter]

In [ ]:
age_filter = (df["number_of_claims"] > 1) | (df["employer"] == "Vipe")
df[age_filter]

In [ ]:
filter_state = df["gender"] == "male"
df[~filter_state]